# GLOBAL VARIABLES
variables:
  HELM_VERSION: 0.1.0

# YML Anchors
.install-deps: &install-deps
  - npm ci --prefix src/

# CI Build Stage
ci-build:
  stage: ci-build
  variables:
    JEST_JUNIT_OUTPUT_DIR: test-output
  script:
    - *install-deps
    - npm run test-lint --prefix src/
    - npm run test-unit --prefix src/
  artifacts:
    when: always
    paths: 
      - src/$JEST_JUNIT_OUTPUT_DIR/junit.xml
    reports:
      junit: src/$JEST_JUNIT_OUTPUT_DIR/junit.xml

# Integration Testing
integration-test:
  stage: integration-testing
  variables:
    JEST_JUNIT_OUTPUT_DIR: test-output
  needs:
    - job: ci-build
  script:
    - *install-deps
    - docker compose -f docker-compose-db.yml up --detach
    - npm run test-integration --prefix src/
    - docker compose -f docker-compose-db.yml down
  artifacts:
    when: always
    paths: 
      - src/$JEST_JUNIT_OUTPUT_DIR/junit.xml
    reports:
      junit: src/$JEST_JUNIT_OUTPUT_DIR/junit.xml

#Build
build-image:
  stage: build-pack
  variables:
    DOCKER_REPO: localhost:5002
  script:
    - docker build -t $DOCKER_REPO/todo:$CI_COMMIT_SHORT_SHA src/.
    - docker login $DOCKER_REPO --username admin -p $dockerPass
    - docker push $DOCKER_REPO/todo:$CI_COMMIT_SHORT_SHA
    - echo "$DOCKER_REPO/todo:$CI_COMMIT_SHORT_SHA" > docker_image.txt
  artifacts:
    when: always
    paths:
      - docker_image.txt


#Package Helm Chart
package-helm:
  stage: build-pack
  only:
    refs:
      - main
  needs:
    - job: build-image
  script:
    - helm package helm/todo --app-version $CI_COMMIT_SHORT_SHA --version $HELM_VERSION
  artifacts:
    when: always
    paths:
      - todo-$HELM_VERSION.tgz

deploy-db-test:
  stage: deploy-test
  variables:
    ENVIRONMENT: test
  only:
    refs:
      - main
  script:
    - sudo su - vagrant -c "helm upgrade database bitnami/mongodb -i --wait --set persistence.enabled=true,auth.enable=false -n $ENVIRONMENT"

deploy-app-test:
  stage: deploy-test
  variables:
    ENVIRONMENT: test
  only:
    refs:
      - main
  needs:
    - job: deploy-db-test
    - job: build-image
    - job: package-helm
  dependencies:
    - build-image
    - package-helm
  script:
    - sudo su - vagrant -c "helm upgrade todo-app ./todo-$HELM_VERSION.tgz -i --wait --set image=$(cat docker_image.txt),podVars.dbHost=database-mongodb.$ENVIRONMENT.svc.cluster.local,podVars.env=$ENVIRONEMNT -n $ENVIRONMENT"
      
# Stages in Pipeline
stages:
  - ci-build
  - integration-testing
  - build-pack
  - package-helm
  - deploy-test
  - deploy-prod