Vagrant.configure("2") do |config|
  config.vm.hostname = "ubuntu"

  config.vm.network "forwarded_port", guest: 80, host: 80

  config.vm.provider :docker do |docker, override|
    override.vm.box = nil
    docker.image = "rofrano/vagrant-provider:ubuntu"
    docker.remains_running = true
    docker.has_ssh = true
    docker.privileged = true
    docker.volumes = ["/sys/fs/cgroup:/sys/fs/cgroup:rw"]
    docker.create_args = ["--cgroupns=host"]
  end  

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook.yml"
  end
end